apiVersion: v1
kind: Secret
metadata:
  name: trading-secrets
  namespace: trading-system
  labels:
    app.kubernetes.io/name: trading-system
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  DB_PASSWORD: cGFzc3dvcmQ=  # password
  
  # JWT Secret (base64 encoded)
  JWT_SECRET: eW91ci0zMi1jaGFyYWN0ZXItand0LXNlY3JldC1rZXktaGVyZQ==  # your-32-character-jwt-secret-key-here
  
  # Redis password (if needed)
  REDIS_PASSWORD: ""
  
  # Grafana admin password (base64 encoded)
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=  # admin

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  namespace: trading-system
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: secrets
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password
  POSTGRES_USER: cG9zdGdyZXM=      # postgres
  POSTGRES_DB: dHJhZGluZ19zeXN0ZW0=  # trading_system 