apiVersion: v1
kind: Service
metadata:
  name: nats-service
  namespace: trading-system
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: message-bus
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 4222
      targetPort: 4222
      protocol: TCP
    - name: monitoring
      port: 8222
      targetPort: 8222
      protocol: TCP
    - name: leafnode
      port: 7422
      targetPort: 7422
      protocol: TCP
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: message-bus 