apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: trading-system
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-exporter
  namespace: trading-system
  labels:
    app.kubernetes.io/name: postgresql-exporter
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql-exporter
    app.kubernetes.io/component: monitoring 