apiVersion: v1
kind: Service
metadata:
  name: trading-core-service
  namespace: trading-system
  labels:
    app.kubernetes.io/name: trading-core
    app.kubernetes.io/component: application
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: trading-core
    app.kubernetes.io/component: application

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-core
  namespace: trading-system
  labels:
    app.kubernetes.io/name: trading-core
    app.kubernetes.io/component: application
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: trading-core
      app.kubernetes.io/component: application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: trading-core
        app.kubernetes.io/component: application
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: trading-core
          image: trading-core:latest  # Replace with your image registry
          imagePullPolicy: Always
          env:
            # Server Configuration
            - name: SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: SERVER_HOST
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: SERVER_PORT
            
            # Database Configuration
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trading-secrets
                  key: DB_PASSWORD
            
            # NATS Configuration
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: NATS_URL
            
            # Redis Configuration
            - name: REDIS_ADDR
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: REDIS_ADDR
            
            # Security
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: trading-secrets
                  key: JWT_SECRET
            
            # Risk Configuration
            - name: RISK_MAX_POSITION_SIZE
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: RISK_MAX_POSITION_SIZE
            - name: RISK_MAX_VAR
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: RISK_MAX_VAR
            - name: RISK_MAX_LEVERAGE
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: RISK_MAX_LEVERAGE
            - name: RISK_MAX_DAILY_LOSS
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: RISK_MAX_DAILY_LOSS
            - name: RISK_MAX_CONCENTRATION
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: RISK_MAX_CONCENTRATION
            
            # Logging Configuration
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: LOG_LEVEL
            - name: LOG_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: LOG_FORMAT
            
            # Environment
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: trading-core-config
                  key: ENVIRONMENT
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 10 